### PR TITLE
Add support for publishing LaserScan messages for sf45b lidar

### PR DESCRIPTION
**Pull request by nakai-omer**

### CODE REVIEW

**Comment by nakai-omer** [comment]
Closed #3

**Comment by Rob2048** [comment]
Hi @nakai-omer, thanks for your interest in helping us improve these drivers. I can't accept your changes in their current form due to the style differences from our original codebase, I hope you understand.

**Comment by nakai-omer** [comment]
Fixing and pushing asap

**Comment by nakai-omer** [comment]
@Rob2048 Fixed

**Comment by Rob2048** [comment]
@nakai-omer Thanks!

**Pull request merged**
